### ISSUE TITLE
Temporal no es thread-safe

### ISSUE THREAD

**Issue by picollomartin** [sisoputnfrba/so-commons-library#87]
La función temporal_get_string_time utiliza la función localtime que no es thread-safe​. Esto afecta por ejemplo a todas las funciones de log cuando la usan.

**Comment by mgarciaisaia** [comment]
Entiendo que esto es by design.

En [el README.md](https://github.com/sisoputnfrba/so-commons-library#notas) hay una nota al respecto:

> Ninguna de las implementaciones utiliza semáforos, por lo que el uso concurrente debe ser implementado por el usuario de estas.

Concurrencia es uno de los temas importantes en la materia para la que desarollamos la biblioteca, por lo que tiene sentido que la biblioteca no lo resuelva :)

Igual preferiría escuchar un par de opiniones más (¿ @gastonprieto, @jazcarate ?)

**Comment by gastonprieto** [comment]
Yo le dije que levante el issue, porque una cosa es sincronizar una biblioteca de listas, colas y demás, que por diseño quiero que las sincronicen. 

Y en este caso es porque cuando hice esa función no me fije que usaba una variable `static` :stuck_out_tongue_winking_eye:, así que para mi deberíamos fixearlo por la función `thread_safe` (fíjate que [acá](https://github.com/sisoputnfrba/so-commons-library/blob/7b3431859db8a057d6582f583b8f933a9ef88a75/src/commons/string.c#L260) también uso la versión  `thread_safe`)

**Comment by jazcarate** [comment]
Si a alguien le importa mi opinion; estoy deacuerdo con Gaston.
Si a alguien no le importa; cree el PR 😸

**Comment by gastonprieto** [comment]
Listo, se mergeo con lo de @jazcarate
